# Generated by Django 3.2.5 on 2021-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('words_cnt', models.IntegerField()),
                ('words_per_sentence', models.IntegerField()),
            ],
        ),
    ]
