# Generated by Django 3.2.5 on 2021-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20210712_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Язык', 'verbose_name_plural': 'Язык'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['title'], 'verbose_name': 'Текст', 'verbose_name_plural': 'Текст'},
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Language'),
        ),
    ]
