# Generated by Django 3.2.5 on 2021-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20210719_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='words_cnt',
        ),
        migrations.RemoveField(
            model_name='text',
            name='words_per_sentence',
        ),
        migrations.AddField(
            model_name='text',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
